name: CI

on:
  push:
    branches:
      - integration
  pull_request:
    branches:
      - integration

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # Lambda runtime 및 프로젝트 요구사항에 맞춘 Node.js 버전 설정
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Set Chrome environment for compatibility
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Run tests with coverage
      - name: Run tests and generate coverage
        run: npm run test:coverage

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # Codecov Token은 GitHub Secrets에 저장되어야 함
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: Frontend-Coverage

      # Ensure compatibility with minimal RAM and disk space
      - name: Check system requirements
        run: |
          free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB\n", $3,$2 }'
          df -h | awk '$NF=="/"{printf "Disk Usage: %d/%dGB\n", $3,$2}'
