name: CI

on:
  push:
    branches:
      - integration
  pull_request:
    branches:
      - integration

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests with coverage
      - name: Run tests and generate coverage
        run: npm run test:coverage

      # Upload coverage to Codecov
      - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: kimjongjip/skku-lifeaa
