name: CI

on:
  push:
    branches:
      - integration
  pull_request:
    branches:
      - integration

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests with coverage
      - name: Run tests and generate coverage
        run: npm run test:coverage

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # GitHub Secrets에서 토큰 가져오기
          files: ./coverage/lcov.info         # 생성된 커버리지 파일 경로
          flags: unittests                    # 태그 지정 (선택 사항)
          name: node-coverage-report          # 리포트 이름 (선택 사항)
          fail_ci_if_error: true              # 업로드 실패 시 CI 실패로 처리
